apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngm-widget
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ngm-widget
  template:
    metadata:
      labels:
        app: ngm-widget
    spec:
      containers:
        - name: ngm-widget
          image: python:3.9-slim:latest
          ports:
            - name: http
              containerPort: 8501
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: ngm-widget
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
