baseline_parameters:
  n_total: !!float  1e7
  # core, children of core, children of non core, non core
  pop_props: [0.05, 0.05, 0.4, 0.5]
  M_novax: [[3.0, 0.0, 0.0, 0.2], [0.5, 0.5, 0.5, 0.5], [0.0, 0.5, 0.5, 0.5], [0.25, 1.0, 1.0, 1.5]]
  ve: 0.74
  p_severe: [0.02, 0.06, 0.6, 0.02]
  G: 10
grid_parameters:
  n_vax_total: [0.0, !!float 2e5, !!float 1e6]
  # vaccination strategy
  vax_strategy: ["0", "1", "2", "even", "0_1"]
