baseline_parameters:
  # total population size
  n_total: !!float 1e7
  # population proportions
  # [core, children, general]
  pop_props: [0.05, 0.45, 0.5]
  ve: 0.74
  beta_high: 10
  beta_low: 1.5
  p_severe: [0.02, 0.06, 0.02]
grid_parameters:
  n_vax_total: [0.0, !!float 2e5, !!float 1e6, !!float 5e6]
  # vaccination strategy
  vax_strategy: ["0", "1", "even"]
